### ISSUE TITLE
iOS support for es2015

### ISSUE THREAD

**Issue by kbwatts** [space-beavers/vote-up#19]
According to [this article](https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html) support for es2015 is on its way which should resolve the following known issues on iOS Safari or Chrome.

![Blank on iOS mobile web](https://cloud.githubusercontent.com/assets/961706/18420158/b0bb7ac0-7820-11e6-889d-c06664f7a0e8.PNG)

![iOS web console view](https://cloud.githubusercontent.com/assets/961706/18420134/7674c61e-7820-11e6-88f0-65f36eb6b231.png)
![1](https://cloud.githubusercontent.com/assets/961706/18420137/7eedf84c-7820-11e6-8087-720a032cf1a0.png)
![2](https://cloud.githubusercontent.com/assets/961706/18420139/7eef5da4-7820-11e6-825c-24f673a2fe8d.png)
![3](https://cloud.githubusercontent.com/assets/961706/18420141/7eefdaf4-7820-11e6-883a-1ec12d066ce5.png)
![4](https://cloud.githubusercontent.com/assets/961706/18420138/7eef71f4-7820-11e6-8a6a-e8b726cbedc4.png)
![5](https://cloud.githubusercontent.com/assets/961706/18420140/7eefcb2c-7820-11e6-8229-5ff4cc4dbb44.png)

**Comment by maxletourneur** [comment]
Has anybody already used a es6 shim or some sort of polyfill for 2015 ?

**Comment by kbwatts** [comment]
Chrome and Safari now support es2015 as of iOSX - issues appear to be resolved.
